# Generated by Django 4.1.7 on 2023-02-19 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='women',
            old_name='is_publisher',
            new_name='is_published',
        ),
    ]
